name: Copy code to WordPress.org Repository

on:
    push:
        branches: [ main ]
    workflow_dispatch:
      
jobs:
  copy_to_wp_repository:
    name: Copy to WP.org
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        path: github_copy

    - name: Install SVN ( Subversion )
      run: |
        sudo apt-get update
        sudo apt-get install subversion

    - name: Checkout WordPress Plugin SVN
      run: |
        svn co http://plugins.svn.wordpress.org/boostrz-tag-manager/ /tmp/boostrz-tag-manager
        cp -r $GITHUB_WORKSPACE/github_copy/* /tmp/boostrz-tag-manager/trunk/
        rm -rf /tmp/boostrz-tag-manager/trunk/.github
        rm -rf /tmp/boostrz-tag-manager/trunk/.git
        rm -rf /tmp/boostrz-tag-manager/trunk/.gitignore
        rm -rf /tmp/boostrz-tag-manager/trunk/.gitattributes
        rm -rf /tmp/boostrz-tag-manager/trunk/.editorconfig
        rm -rf /tmp/boostrz-tag-manager/trunk/.vscode

    - name: WordPress SVN Copy
      run: |
        cd /tmp/boostrz-tag-manager/trunk/
        svn add *
        if svn status | grep -q '^[ACDMR?!]'; then
            svn commit -m "Update from GitHub Actions" --username ${{ secrets.WP_SVN_USERNAME }} --password ${{ secrets.WP_SVN_PASSWORD }}
        else
            echo "No changes detected"
        fi


